//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:15:36 PM PST 
//

package edu.iris.dmc.fdsn.station.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Equivalent to SEED blockette 52 and parent element for the related the
 * response blockettes.
 * 
 * <p>
 * Java class for ChannelType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ChannelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseNodeType">
 *       &lt;sequence>
 *         &lt;element name="ExternalReference" type="{http://www.fdsn.org/xml/station/1}ExternalReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TerminationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Latitude" type="{http://www.fdsn.org/xml/station/1}LatitudeType"/>
 *         &lt;element name="Longitude" type="{http://www.fdsn.org/xml/station/1}LongitudeType"/>
 *         &lt;element name="Elevation" type="{http://www.fdsn.org/xml/station/1}DistanceType"/>
 *         &lt;element name="Depth" type="{http://www.fdsn.org/xml/station/1}DistanceType"/>
 *         &lt;element name="Azimuth" type="{http://www.fdsn.org/xml/station/1}AzimuthType" minOccurs="0"/>
 *         &lt;element name="Dip" type="{http://www.fdsn.org/xml/station/1}DipType" minOccurs="0"/>
 *         &lt;element name="Type" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="TRIGGERED"/>
 *               &lt;enumeration value="CONTINUOUS"/>
 *               &lt;enumeration value="HEALTH"/>
 *               &lt;enumeration value="GEOPHYSICAL"/>
 *               &lt;enumeration value="WEATHER"/>
 *               &lt;enumeration value="FLAG"/>
 *               &lt;enumeration value="SYNTHESIZED"/>
 *               &lt;enumeration value="INPUT"/>
 *               &lt;enumeration value="EXPERIMENTAL"/>
 *               &lt;enumeration value="MAINTENANCE"/>
 *               &lt;enumeration value="BEAM"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;group ref="{http://www.fdsn.org/xml/station/1}SampleRateGroup" minOccurs="0"/>
 *         &lt;element name="StorageFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClockDrift" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.fdsn.org/xml/station/1>FloatType">
 *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SECONDS/SAMPLE" />
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CalibrationUnits" type="{http://www.fdsn.org/xml/station/1}UnitsType" minOccurs="0"/>
 *         &lt;element name="Sensor" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/>
 *         &lt;element name="PreAmplifier" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/>
 *         &lt;element name="DataLogger" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/>
 *         &lt;element name="Response" type="{http://www.fdsn.org/xml/station/1}ResponseType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="locationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChannelType", propOrder = { "externalReference", "latitude",
		"longitude", "elevation", "depth", "azimuth", "dip", "type",
		"sampleRate", "sampleRateRatio", "storageFormat", "clockDrift",
		"calibrationUnits", "sensor", "preAmplifier", "dataLogger",
		"equipment", "response" })
public class Channel extends BaseNodeType {

	@XmlElement(name = "ExternalReference")
	protected List<ExternalReferenceType> externalReference;
	@XmlElement(name = "Latitude", required = true)
	protected Latitude latitude;
	@XmlElement(name = "Longitude", required = true)
	protected Longitude longitude;
	@XmlElement(name = "Elevation", required = true)
	protected Distance elevation;
	@XmlElement(name = "Depth", required = true)
	protected Distance depth;
	@XmlElement(name = "Azimuth")
	protected Azimuth azimuth;
	@XmlElement(name = "Dip")
	protected Dip dip;
	@XmlElement(name = "Type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected List<String> type;
	@XmlElement(name = "SampleRate")
	protected SampleRate sampleRate;
	@XmlElement(name = "SampleRateRatio")
	protected SampleRateRatioType sampleRateRatio;
	@XmlElement(name = "StorageFormat")
	protected String storageFormat;
	@XmlElement(name = "ClockDrift")
	protected Channel.ClockDrift clockDrift;
	@XmlElement(name = "CalibrationUnits")
	protected Units calibrationUnits;
	@XmlElement(name = "Sensor")
	protected Equipment sensor;
	@XmlElement(name = "PreAmplifier")
	protected Equipment preAmplifier;
	@XmlElement(name = "DataLogger")
	protected Equipment dataLogger;
	@XmlElement(name = "Equipment")
	protected Equipment equipment;
	@XmlElement(name = "Response")
	protected Response response;
	@XmlAttribute(name = "locationCode", required = true)
	protected String locationCode;

	@XmlTransient
	private Station station;

	public Station getStation() {
		return this.station;
	}

	public void afterUnmarshal(Unmarshaller u, Object parent) {
		this.station = (Station) parent;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public void add(Comment comment) {
		if (comment == null) {
			return;
		}
		if (this.comment == null) {
			this.comment = new ArrayList<Comment>();
		}
		this.comment.add(comment);
	}

	/**
	 * Gets the value of the externalReference property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the externalReference property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExternalReference().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ExternalReferenceType }
	 * 
	 * 
	 */
	public List<ExternalReferenceType> getExternalReference() {
		if (externalReference == null) {
			externalReference = new ArrayList<ExternalReferenceType>();
		}
		return this.externalReference;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return possible object is {@link Latitude }
	 * 
	 */
	public Latitude getLatitude() {
		return latitude;
	}

	public Double getLatitudeValue() {
		if (latitude == null) {
			return null;
		}
		return latitude.getValue();
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Latitude }
	 * 
	 */
	public void setLatitude(Latitude value) {
		this.latitude = value;
	}

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return possible object is {@link Longitude }
	 * 
	 */
	public Longitude getLongitude() {
		return longitude;
	}

	public Double getLongitudeValue() {
		if (longitude == null) {
			return null;
		}
		return longitude.getValue();
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Longitude }
	 * 
	 */
	public void setLongitude(Longitude value) {
		this.longitude = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link Distance }
	 * 
	 */
	public Distance getElevation() {
		return elevation;
	}

	public Double getElevationValue() {
		if (elevation == null) {
			return null;
		}
		return elevation.getValue();
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value
	 *            allowed object is {@link Distance }
	 * 
	 */
	public void setElevation(Distance value) {
		this.elevation = value;
	}

	/**
	 * Gets the value of the depth property.
	 * 
	 * @return possible object is {@link Distance }
	 * 
	 */
	public Distance getDepth() {
		return depth;
	}

	public Double getDepthValue() {
		if (depth == null) {
			return null;
		}
		return depth.getValue();
	}

	/**
	 * Sets the value of the depth property.
	 * 
	 * @param value
	 *            allowed object is {@link Distance }
	 * 
	 */
	public void setDepth(Distance value) {
		this.depth = value;
	}

	/**
	 * Gets the value of the azimuth property.
	 * 
	 * @return possible object is {@link Azimuth }
	 * 
	 */
	public Azimuth getAzimuth() {
		return azimuth;
	}

	public Double getAzimuthValue() {
		if (azimuth == null) {
			return null;
		}
		return azimuth.getValue();
	}

	/**
	 * Sets the value of the azimuth property.
	 * 
	 * @param value
	 *            allowed object is {@link Azimuth }
	 * 
	 */
	public void setAzimuth(Azimuth value) {
		this.azimuth = value;
	}

	/**
	 * Gets the value of the dip property.
	 * 
	 * @return possible object is {@link Dip }
	 * 
	 */
	public Dip getDip() {
		return dip;
	}

	public Double getDipValue() {
		if (dip == null) {
			return null;
		}
		return dip.getValue();
	}

	/**
	 * Sets the value of the dip property.
	 * 
	 * @param value
	 *            allowed object is {@link Dip }
	 * 
	 */
	public void setDip(Dip value) {
		this.dip = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the type property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getType() {
		if (type == null) {
			type = new ArrayList<String>();
		}
		return this.type;
	}

	public void setType(List<String> type) {
		this.type = type;
	}

	public void addType(String type) {

		if (this.type == null) {
			this.type = new ArrayList<String>();
		}
		if (type == null) {
			return;
		}
		this.type.add(type);
	}

	/**
	 * Gets the value of the sampleRate property.
	 * 
	 * @return possible object is {@link SampleRate }
	 * 
	 */
	public SampleRate getSampleRate() {
		return sampleRate;
	}

	public Double getSampleRateValue() {
		if (sampleRate == null) {
			return null;
		}
		return sampleRate.getValue();
	}

	/**
	 * Sets the value of the sampleRate property.
	 * 
	 * @param value
	 *            allowed object is {@link SampleRate }
	 * 
	 */
	public void setSampleRate(SampleRate value) {
		this.sampleRate = value;
	}

	/**
	 * Gets the value of the sampleRateRatio property.
	 * 
	 * @return possible object is {@link SampleRateRatioType }
	 * 
	 */
	public SampleRateRatioType getSampleRateRatio() {
		return sampleRateRatio;
	}

	/**
	 * Sets the value of the sampleRateRatio property.
	 * 
	 * @param value
	 *            allowed object is {@link SampleRateRatioType }
	 * 
	 */
	public void setSampleRateRatio(SampleRateRatioType value) {
		this.sampleRateRatio = value;
	}

	/**
	 * Gets the value of the storageFormat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStorageFormat() {
		return storageFormat;
	}

	/**
	 * Sets the value of the storageFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStorageFormat(String value) {
		this.storageFormat = value;
	}

	/**
	 * Gets the value of the clockDrift property.
	 * 
	 * @return possible object is {@link Channel.ClockDrift }
	 * 
	 */
	public Channel.ClockDrift getClockDrift() {
		return clockDrift;
	}

	/**
	 * Sets the value of the clockDrift property.
	 * 
	 * @param value
	 *            allowed object is {@link Channel.ClockDrift }
	 * 
	 */
	public void setClockDrift(Channel.ClockDrift value) {
		this.clockDrift = value;
	}

	/**
	 * Gets the value of the calibrationUnits property.
	 * 
	 * @return possible object is {@link Units }
	 * 
	 */
	public Units getCalibrationUnits() {
		return calibrationUnits;
	}

	/**
	 * Sets the value of the calibrationUnits property.
	 * 
	 * @param value
	 *            allowed object is {@link Units }
	 * 
	 */
	public void setCalibrationUnits(Units value) {
		this.calibrationUnits = value;
	}

	/**
	 * Gets the value of the sensor property.
	 * 
	 * @return possible object is {@link Equipment }
	 * 
	 */
	public Equipment getSensor() {
		return sensor;
	}

	/**
	 * Sets the value of the sensor property.
	 * 
	 * @param value
	 *            allowed object is {@link Equipment }
	 * 
	 */
	public void setSensor(Equipment value) {
		this.sensor = value;
	}

	/**
	 * Gets the value of the preAmplifier property.
	 * 
	 * @return possible object is {@link Equipment }
	 * 
	 */
	public Equipment getPreAmplifier() {
		return preAmplifier;
	}

	/**
	 * Sets the value of the preAmplifier property.
	 * 
	 * @param value
	 *            allowed object is {@link Equipment }
	 * 
	 */
	public void setPreAmplifier(Equipment value) {
		this.preAmplifier = value;
	}

	/**
	 * Gets the value of the dataLogger property.
	 * 
	 * @return possible object is {@link Equipment }
	 * 
	 */
	public Equipment getDataLogger() {
		return dataLogger;
	}

	/**
	 * Sets the value of the dataLogger property.
	 * 
	 * @param value
	 *            allowed object is {@link Equipment }
	 * 
	 */
	public void setDataLogger(Equipment value) {
		this.dataLogger = value;
	}

	/**
	 * Gets the value of the equipment property.
	 * 
	 * @return possible object is {@link EquipmentType }
	 * 
	 */
	public Equipment getEquipment() {
		return equipment;
	}

	/**
	 * Sets the value of the equipment property.
	 * 
	 * @param value
	 *            allowed object is {@link EquipmentType }
	 * 
	 */
	public void setEquipment(Equipment value) {
		this.equipment = value;
	}

	/**
	 * Gets the value of the response property.
	 * 
	 * @return possible object is {@link Response }
	 * 
	 */
	public Response getResponse() {
		return response;
	}

	/**
	 * Sets the value of the response property.
	 * 
	 * @param value
	 *            allowed object is {@link Response }
	 * 
	 */
	public void setResponse(Response value) {
		this.response = value;
	}

	/**
	 * Gets the value of the locationCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocationCode() {
		if (locationCode != null) {
			return locationCode.trim();
		}
		return locationCode;
	}

	/**
	 * Sets the value of the locationCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocationCode(String value) {
		this.locationCode = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;restriction base="&lt;http://www.fdsn.org/xml/station/1>FloatType">
	 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SECONDS/SAMPLE" />
	 *     &lt;/restriction>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class ClockDrift extends Float {

	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
		result = prime * result
				+ ((startDate == null) ? 0 : startDate.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Channel other = (Channel) obj;
		if (station == null) {
			if (other.station != null)
				return false;
		} else if (!station.equals(other.station))
			return false;

		if (locationCode == null) {
			if (other.locationCode != null)
				return false;
		} else if (!locationCode.equals(other.locationCode))
			return false;

		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (endDate == null) {
			if (other.endDate != null)
				return false;
		} else if (!endDate.equals(other.endDate))
			return false;
		if (startDate == null) {
			if (other.startDate != null)
				return false;
		} else if (!startDate.equals(other.startDate))
			return false;

		return true;
	}

	@Override
	public String toString() {
		return "Channel [code=" + code + ", locationCode=" + locationCode
				+ ", startDate=" + startDate + ", endDate=" + endDate + "]";
	}

}
