//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:15:36 PM PST 
//


package edu.iris.dmc.fdsn.station.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Representation of floating-point numbers used as
 * 				measurements.
 * 
 * <p>Java class for FloatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FloatType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *       &lt;attGroup ref="{http://www.fdsn.org/xml/station/1}uncertaintyDouble"/>
 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FloatType", propOrder = {
    "value"
})
@XmlSeeAlso({
    Azimuth.class,
    Dip.class,
    VoltageType.class,
    Frequency.class,
    Distance.class,
    SampleRate.class,
    LongitudeBaseType.class,
    SecondType.class,
    AngleType.class,
    LatitudeBaseType.class,
    edu.iris.dmc.fdsn.station.model.Channel.ClockDrift.class
})
public class Float {

    @XmlValue
    protected double value;
    @XmlAttribute(name = "unit")
    protected String unit;
    @XmlAttribute(name = "plusError")
    protected Double plusError;
    @XmlAttribute(name = "minusError")
    protected Double minusError;

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the plusError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPlusError() {
        return plusError;
    }

    /**
     * Sets the value of the plusError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPlusError(Double value) {
        this.plusError = value;
    }

    /**
     * Gets the value of the minusError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinusError() {
        return minusError;
    }

    /**
     * Sets the value of the minusError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinusError(Double value) {
        this.minusError = value;
    }

}
