//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:15:36 PM PST 
//


package edu.iris.dmc.fdsn.station.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.iris.fsdn.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FDSNStationXML_QNAME = new QName("http://www.fdsn.org/xml/station/1", "FDSNStationXML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.iris.fsdn.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannelType() {
        return new Channel();
    }

    /**
     * Create an instance of {@link FIR }
     * 
     */
    public FIR createFIRType() {
        return new FIR();
    }

    /**
     * Create an instance of {@link Polynomial }
     * 
     */
    public Polynomial createPolynomialType() {
        return new Polynomial();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStationType() {
        return new Station();
    }

    /**
     * Create an instance of {@link FDSNStationXML }
     * 
     */
    public FDSNStationXML createRootType() {
        return new FDSNStationXML();
    }

    /**
     * Create an instance of {@link ResponseListElement }
     * 
     */
    public ResponseListElement createResponseListElementType() {
        return new ResponseListElement();
    }

    /**
     * Create an instance of {@link Gain }
     * 
     */
    public Gain createGainType() {
        return new Gain();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponseType() {
        return new Response();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSiteType() {
        return new Site();
    }

    /**
     * Create an instance of {@link Azimuth }
     * 
     */
    public Azimuth createAzimuthType() {
        return new Azimuth();
    }

    /**
     * Create an instance of {@link LogType }
     * 
     */
    public LogType createLogType() {
        return new LogType();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createCommentType() {
        return new Comment();
    }

    /**
     * Create an instance of {@link PoleZero }
     * 
     */
    public PoleZero createPoleZeroType() {
        return new PoleZero();
    }

    /**
     * Create an instance of {@link Dip }
     * 
     */
    public Dip createDipType() {
        return new Dip();
    }

    /**
     * Create an instance of {@link Float }
     * 
     */
    public Float createFloatType() {
        return new Float();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetworkType() {
        return new Network();
    }

    /**
     * Create an instance of {@link VoltageType }
     * 
     */
    public VoltageType createVoltageType() {
        return new VoltageType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link Coefficients }
     * 
     */
    public Coefficients createCoefficientsType() {
        return new Coefficients();
    }

    /**
     * Create an instance of {@link BaseFilter }
     * 
     */
    public BaseFilter createBaseFilterType() {
        return new BaseFilter();
    }

    /**
     * Create an instance of {@link Frequency }
     * 
     */
    public Frequency createFrequencyType() {
        return new Frequency();
    }

    /**
     * Create an instance of {@link Distance }
     * 
     */
    public Distance createDistanceType() {
        return new Distance();
    }

    /**
     * Create an instance of {@link BaseNodeType }
     * 
     */
    public BaseNodeType createBaseNodeType() {
        return new BaseNodeType();
    }

    /**
     * Create an instance of {@link Sensitivity }
     * 
     */
    public Sensitivity createSensitivityType() {
        return new Sensitivity();
    }

    /**
     * Create an instance of {@link SampleRateRatioType }
     * 
     */
    public SampleRateRatioType createSampleRateRatioType() {
        return new SampleRateRatioType();
    }

    /**
     * Create an instance of {@link Longitude }
     * 
     */
    public Longitude createLongitudeType() {
        return new Longitude();
    }

    /**
     * Create an instance of {@link SampleRate }
     * 
     */
    public SampleRate createSampleRateType() {
        return new SampleRate();
    }

    /**
     * Create an instance of {@link LatitudeBaseType }
     * 
     */
    public LatitudeBaseType createLatitudeBaseType() {
        return new LatitudeBaseType();
    }

    /**
     * Create an instance of {@link LongitudeBaseType }
     * 
     */
    public LongitudeBaseType createLongitudeBaseType() {
        return new LongitudeBaseType();
    }

    /**
     * Create an instance of {@link Equipment }
     * 
     */
    public Equipment createEquipmentType() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link ResponseList }
     * 
     */
    public ResponseList createResponseListType() {
        return new ResponseList();
    }

    /**
     * Create an instance of {@link ResponseStage }
     * 
     */
    public ResponseStage createResponseStageType() {
        return new ResponseStage();
    }

    /**
     * Create an instance of {@link ExternalReferenceType }
     * 
     */
    public ExternalReferenceType createExternalReferenceType() {
        return new ExternalReferenceType();
    }

    /**
     * Create an instance of {@link SecondType }
     * 
     */
    public SecondType createSecondType() {
        return new SecondType();
    }

    /**
     * Create an instance of {@link PhoneNumberType }
     * 
     */
    public PhoneNumberType createPhoneNumberType() {
        return new PhoneNumberType();
    }

    /**
     * Create an instance of {@link Units }
     * 
     */
    public Units createUnitsType() {
        return new Units();
    }

    /**
     * Create an instance of {@link Decimation }
     * 
     */
    public Decimation createDecimationType() {
        return new Decimation();
    }

    /**
     * Create an instance of {@link AngleType }
     * 
     */
    public AngleType createAngleType() {
        return new AngleType();
    }

    /**
     * Create an instance of {@link Latitude }
     * 
     */
    public Latitude createLatitudeType() {
        return new Latitude();
    }

    /**
     * Create an instance of {@link PolesZeros }
     * 
     */
    public PolesZeros createPolesZerosType() {
        return new PolesZeros();
    }

    /**
     * Create an instance of {@link FloatNoUnitType }
     * 
     */
    public FloatNoUnitType createFloatNoUnitType() {
        return new FloatNoUnitType();
    }

    /**
     * Create an instance of {@link Channel.ClockDrift }
     * 
     */
    public Channel.ClockDrift createChannelTypeClockDrift() {
        return new Channel.ClockDrift();
    }

    /**
     * Create an instance of {@link FIR.NumeratorCoefficient }
     * 
     */
    public FIR.NumeratorCoefficient createFIRTypeNumeratorCoefficient() {
        return new FIR.NumeratorCoefficient();
    }

    /**
     * Create an instance of {@link Polynomial.Coefficient }
     * 
     */
    public Polynomial.Coefficient createPolynomialTypeCoefficient() {
        return new Polynomial.Coefficient();
    }

    /**
     * Create an instance of {@link Station.Operator }
     * 
     */
    public Station.Operator createStationTypeOperator() {
        return new Station.Operator();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FDSNStationXML }{@code >}}
     * 
     */
    /*@XmlElementDecl(namespace = "http://www.fdsn.org/xml/station/1", name = "FDSNStationXML")
    public JAXBElement<FDSNStationXML> createFDSNStationXML(FDSNStationXML value) {
        return new JAXBElement<FDSNStationXML>(_FDSNStationXML_QNAME, FDSNStationXML.class, null, value);
    }*/
   // @XmlElementDecl(namespace = "http://www.fdsn.org/xml/station/1", name = "FDSNStationXML")
    public FDSNStationXML createFDSNStationXML() {
        return new FDSNStationXML();
    }
}
