//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:15:36 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fdsn.org/xml/station/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.iris.dmc.fdsn.station.model;
