//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:15:36 PM PST 
//


package edu.iris.dmc.fdsn.station.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Response: complex poles and zeros. Corresponds to SEED blockette
 * 				53.
 * 
 * <p>Java class for PolesZerosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolesZerosType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType">
 *       &lt;sequence>
 *         &lt;element name="PzTransferFunctionType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="LAPLACE (RADIANS/SECCOND)"/>
 *               &lt;enumeration value="LAPLACE (HERTZ)"/>
 *               &lt;enumeration value="DIGITAL (Z-TRANSFORM)"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NormalizationFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="NormalizationFrequency" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/>
 *         &lt;element name="Pole" type="{http://www.fdsn.org/xml/station/1}PoleZeroType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Zero" type="{http://www.fdsn.org/xml/station/1}PoleZeroType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolesZerosType", propOrder = {
    "pzTransferFunctionType",
    "normalizationFactor",
    "normalizationFrequency",
    "zero",
    "pole"
})
public class PolesZeros
    extends BaseFilter
{

    @XmlElement(name = "PzTransferFunctionType", required = true)
    protected String pzTransferFunctionType;
    @XmlElement(name = "NormalizationFactor", defaultValue = "1.0")
    protected double normalizationFactor;
    @XmlElement(name = "NormalizationFrequency", required = true)
    protected Frequency normalizationFrequency;
    @XmlElement(name = "Pole")
    protected List<PoleZero> pole;
    @XmlElement(name = "Zero")
    protected List<PoleZero> zero;

    /**
     * Gets the value of the pzTransferFunctionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPzTransferFunctionType() {
        return pzTransferFunctionType;
    }

    /**
     * Sets the value of the pzTransferFunctionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPzTransferFunctionType(String value) {
        this.pzTransferFunctionType = value;
    }

    /**
     * Gets the value of the normalizationFactor property.
     * 
     */
    public double getNormalizationFactor() {
        return normalizationFactor;
    }

    /**
     * Sets the value of the normalizationFactor property.
     * 
     */
    public void setNormalizationFactor(double value) {
        this.normalizationFactor = value;
    }

    /**
     * Gets the value of the normalizationFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getNormalizationFrequency() {
        return normalizationFrequency;
    }

    /**
     * Sets the value of the normalizationFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setNormalizationFrequency(Frequency value) {
        this.normalizationFrequency = value;
    }

    /**
     * Gets the value of the pole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoleZero }
     * 
     * 
     */
    public List<PoleZero> getPole() {
        if (pole == null) {
            pole = new ArrayList<PoleZero>();
        }
        return this.pole;
    }

    /**
     * Gets the value of the zero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoleZero }
     * 
     * 
     */
    public List<PoleZero> getZero() {
        if (zero == null) {
            zero = new ArrayList<PoleZero>();
        }
        return this.zero;
    }

}
