//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:15:36 PM PST 
//


package edu.iris.dmc.fdsn.station.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  Complex numbers used as poles or zeros in channel
 * 				response.
 * 
 * <p>Java class for PoleZeroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoleZeroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Real" type="{http://www.fdsn.org/xml/station/1}FloatNoUnitType"/>
 *         &lt;element name="Imaginary" type="{http://www.fdsn.org/xml/station/1}FloatNoUnitType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoleZeroType", propOrder = {
    "real",
    "imaginary"
})
public class PoleZero {

    @XmlElement(name = "Real", required = true)
    protected FloatNoUnitType real;
    @XmlElement(name = "Imaginary", required = true)
    protected FloatNoUnitType imaginary;
    @XmlAttribute(name = "number")
    protected BigInteger number;

    /**
     * Gets the value of the real property.
     * 
     * @return
     *     possible object is
     *     {@link FloatNoUnitType }
     *     
     */
    public FloatNoUnitType getReal() {
        return real;
    }

    /**
     * Sets the value of the real property.
     * 
     * @param value
     *     allowed object is
     *     {@link FloatNoUnitType }
     *     
     */
    public void setReal(FloatNoUnitType value) {
        this.real = value;
    }

    /**
     * Gets the value of the imaginary property.
     * 
     * @return
     *     possible object is
     *     {@link FloatNoUnitType }
     *     
     */
    public FloatNoUnitType getImaginary() {
        return imaginary;
    }

    /**
     * Sets the value of the imaginary property.
     * 
     * @param value
     *     allowed object is
     *     {@link FloatNoUnitType }
     *     
     */
    public void setImaginary(FloatNoUnitType value) {
        this.imaginary = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

}
